flaskr/__init__.py
import os
from flask import Flask
from .routes.route import bp
from .routes.apiroute import apibp

def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.sqlite'),
    )

    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    app.register_blueprint(bp)
    app.register_blueprint(apibp)

    return app

flaskr/controllers/get_problem.py
from flask import jsonify
from ..database.db import connect_db
import sqlite3

# logic to fetch problem data from database
def get_problems(): 
    db = connect_db()
    db.row_factory = sqlite3.Row
    cur = db.cursor()

    cur.execute("DROP TABLE IF EXISTS problems")
    cur.execute("CREATE TABLE problems (pid integer primary key autoincrement, problem_name text, date_solved date, time_taken int)")
    cur.execute("INSERT INTO problems (problem_name, date_solved, time_taken) VALUES ('Two Sum', '2025-06-28', 15)")
    cur.execute("INSERT INTO problems (problem_name, date_solved, time_taken) VALUES ('Is Anagram', '2025-06-29', 10)")
    results = cur.execute("SELECT problem_name, date_solved, time_taken FROM problems")

    completed_problems = [tuple(row) for row in results.fetchall()]
    return completed_problems 

flaskr/controllers/index.py
from flask import render_template

def index_page(): 
    return render_template('index.html')

flaskr/controllers/problem.py
from flask import jsonify
from ..database.db import connect_db
import sqlite3

def get_problems(): 
    db = connect_db()
    db.row_factory = sqlite3.Row
    cur = db.cursor()

    cur.execute("DROP TABLE IF EXISTS problems")
    cur.execute("CREATE TABLE problems (pid integer primary key autoincrement, problem_name text, date_solved date, time_taken int)")
    cur.execute("INSERT INTO problems (problem_name, date_solved, time_taken) VALUES ('Two Sum', '2025-06-28', 15)")
    results = cur.execute("SELECT problem_name, date_solved, time_taken FROM problems")


    problem_info = results.fetchall()
    row = problem_info[0]
    return f"<h1>Name: {row['problem_name']}, <br>Date Solved: {row['date_solved']}, <br>Time Taken: {row['time_taken']} minutes"

flaskr/controllers/problemlist.py
from flask import render_template
from .get_problem import get_problems

# rendering the problem list page 
def problemlist_page():
    problems = get_problems()
    return render_template('problemlist.html', problems=problems)

flaskr/routes/apiroute.py
from flask import Blueprint
from ..controllers.get_problem import get_problems

apibp = Blueprint('api', __name__, url_prefix='/api')

#api is used for data serving routes 

@apibp.route('/problem')
def get_problems_route():
    return get_problems()

flaskr/routes/route.py
from flask import Blueprint
from ..controllers.index import index_page
from ..controllers.problemlist import problemlist_page

bp = Blueprint('main', __name__)

# this file serves to handle the basic page layouts
# stores different routes for the app
@bp.route('/')
def index():
    return index_page()

@bp.route('/problemlist')
def problemlist(): 
    return problemlist_page()

flaskr/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <span>Home Page</span>
    <br>
    <button><a href="{{ url_for('main.problemlist') }}">View Problems</a></button>
</body>
</html>

flaskr/templates/problemlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <span>Problem List</span>
    <br>
    <ul> 
        {% for problem in problems %}
            <li>
                <strong>{{ problem[0] }}</strong><br>
                Date Solved: {{ problem[1] }}<br>
                Time Taken: {{ problem[2] }} minutes
            </li>
        {% endfor %}
    </ul>
</body>
</html>